### ISSUE TITLE
Code does not work in Windows OS

### ISSUE THREAD

**Issue by ozebehnam** [FredHutch/storage-crawler#11]
hey there,
it's not clear how to run your code in Windows or other OS, please write a complete guide to make your code useful!
any time that I ran your code using python interpreter in Windows CMD it says ;
Traceback (most recent call last):
  File "storcrawl.py", line 3, in <module>
    import configargparse
ImportError: No module named configargparse
and even running it in IDE also is not possible and it says :
usage: storcrawl.py [-h] [-c CONFIG_FILE] [-d] [-v] [-o OWNERS]
                    [-e EXTENSION_LENGTH] -H DBHOST -p DBPORT -U DBUSER -P
                    DBPASS -N DBNAME [-l LOGDIR] -D DIR [-E EXCLUDE]
                    [-w WALKERS] [-s STATERS] [-i INJECTS] [-u UPDATE]
                    [-T TIMEOUT] -t TAG [-x REPORTING_USER]
                    [-y REPORTING_PASS]
storcrawl.py: error: the following arguments are required: -H/--dbhost, -p/--dbport, -U/--dbuser, -P/--dbpass, -N/--dbname, -D/--dir, -t/--tag

**even it's really not clear where to config PostgreSQL credentials and it really makes me confused for running!**

**Comment by fizwit** [comment]
Store crawl was not designed to work on personal computers.
